from pymongo import MongoClient

client = MongoClient(
    "mongodb://root:root@mongo1:30001/policies?authSource=admin", 27017
)
db = client["policies"]
collection = db["censusanswers"]

number_of_documents = 100000

for _ in range(number_of_documents):
    document = {
        "documentId": "616976f18ca7d1001dd34c7a",
        "campaignCode": "mdc_intellify_demographics_data",
        "clientOneCode": "DEV_BUG",
        "comment": "comment 1",
        "submitDate": "2023-11-27T14:10:40.079Z",
        "userEmail": "test@test.com",
        "fullDocument": True,
        "answers": {
            "INT_MED_EE_CONT": "-0.34",
            "INT_STATUS": "active",
            "INT_CLASS": "Full time",
            "INT_DATE_OF_BIRTH": "1956-06-26",
            "INT_DATE_OF_HIRE": "2004-10-04",
            "INT_GENDER": "Other",
            "INT_INCOME_SALARY": "99000",
            "INT_PAY_BAND": "< 500k",
            "INT_RESIDENCE_STATE": "Georgia",
            "INT_HOME_ZIP": "02113",
            "INT_WORK_ZIP": "93602",
            "INT_WORK_LOCATION": "California",
            "INT_DEPARTMENT": "Sales Depatment",
            "INT_JOB_CATEGORY": "Manager",
            "INT_APPLICABLE_YEAR": 2014,
            "INT_MEDICAL_ELECTION": "SEL",
            "INT_MEDICAL_CARRIER": "New insurrer",
            "INT_MEDICAL_PLAN": "med plan spouse enrolled",
            "INT_SURCHARGE_TOBACO": "YES",
            "INT_SURCHARGE_WORKING_SPOUSE": "YES",
            "INT_DENTAL_ELECTION": "SEL",
            "INT_DENTAL_CARRIER": "New insurrer",
            "INT_DENTAL_PLAN": "Plan plan48",
            "INT_DENTAL_TYPE": "DHMO",
            "INT_DENTAL_TIER": "Employee + Spouse",
            "INT_VISION_ELECTION": "ineligible",
            "INT_VISION_CARRIER": "New insurrer",
            "INT_VISION_PLAN": "TEST VISION 46",
            "INT_VISION_TIER": "Employee + Child(ren)",
            "INT_HSA_ELECTION_EMPLOYER": "123456",
            "INT_AMOUNT_HSA_ER": "56m",
            "INT_HSA_ELECTION_EMPLOYEE": "78600",
            "INT_HEALTH_CARE_FSA_ELECTION": "Waived",
            "INT_HEALTH_CARE_FSA_SUM": "123456",
            "INT_AMOUNT_FSA_HC": "150k",
            "INT_DEPENDENT_CARE_FSA_ELECTION": "Waived",
            "INT_DEPENDENT_CARE_FSA_SUM": "1",
            "INT_AMOUNT_FSA_DC": "123456",
            "INT_DATE_OF_TERMINATION": "2004-10-04",
            "INT_DATE_OF_DISABILITY_START": "2004-10-04",
            "INT_DATE_OF_DISABLITY_END": "10/04/2004",
            "INT_DATE_OF_RETIREMENT": "2004-10-04",
            "INT_HOME_CITY": "Orlando",
            "INT_HOME_STATE": "Georgia",
            "INT_HOME_COUNTRY": "United States",
            "INT_WORK_CITY": "Henderson",
            "INT_JOB_GRADE": "Job grade 4",
            "INT_JOB_TITLE": "Office manager",
            "INT_REPORTING_HIERARCHY": "cost center",
            "INT_EMPLOYER_CONTRIBUTION": "65k",
            "INT_DENTAL_ELIGIBILITY": "eligible",
            "INT_VISION_ELIGIBILITY": "eligible",
            "INT_LIMITED_PURPOSE_FSA_ELECTION": "Elected",
            "INT_LIMITED_PURPOSE_FSA_SUM": "22",
            "INT_FSA_TRANSIT_ELECTION": "cov",
            "INT_FSA_PARKING_ELECTION": "Waived",
            "INT_IDENTITY_FORCE_ELECTION": "Elected",
            "INT_IDENTIFY_FORCE_TIER": "Employee + 2+",
            "INT_BASIC_LIFE_SUM": "20",
            "INT_VOLUNTARY_LIFE_ELECTION": "cov",
            "INT_VOLUNTARY_LIFE_SUM": "500000000",
            "INT_SPOUSE_LIFE_ELECTION": "cov",
            "INT_SPOUSE_LIFE_SUM": "143588",
            "INT_CHILD_LIFE_ELECTION": "Elected",
            "INT_CHILD_LIFE_SUM": "55000",
            "INT_ADND_ELECTION": "Elected",
            "INT_ADND_SUM": "55000",
            "INT_ADND_TIER": "employee",
            "INT_STD_ELECTION": "Waived",
            "INT_VOLUNTARY_BENEFIT": "Waived",
            "INT_DOMESTIC_PARTNER": "NO",
            "CLIENT_EXCLUDE_EMPLOYEE": "no",
            "SYSTEM_EXCLUDE_EMPLOYEE": "no",
            "INT_ALL_ID": "7587426869400691",
            "INT_MEDICAL_TYPE": "",
            "INT_MEDICAL_TIER": "Employee Only",
            "INT_HSA_ELECTION": "",
            "INT_FSA_TRANSIT_SUM": "",
            "INT_FSA_PARKING_SUM": "",
            "INT_LTD_ELECTION": "",
            "AGE": 67,
            "TENURE": 19,
            "REGION": "Northeast",
        },
        "contextData": {
            "companyId": "61692ad50e56d4001d9562b0",
            "campaignId": "60ffe62153d6c1001afdc7a7",
            "campaignCode": "mdc_intellify_demographics_data",
            "submissionDate": "2021-10-15T12:41:20.974Z",
            "submissionId": "616976d8800f68001ebf2e70",
            "grpCode": "INT111",
            "ctryCode": "US",
            "orgSize": None,
            "industry": {"superSector": "HT", "sector": "196", "subSector": "2060"},
            "orgReferenceCode": "INT111",
            "companyReferenceCode": "GENT22",
            "sectionCode": "INT_ALL_DATA",
        },
        "__v": 0,
        "createdAt": "2023-11-28T17:54:52.945Z",
        "updatedAt": "2024-02-28T22:52:39.826Z",
    }
    collection.insert_one(document)

client.close()
print(f"Inserted {number_of_documents} documents")
